$.extend({alert: function (message, title) {$("<div></div>").dialog( {buttons:{"Cerrar": function (){$(this).dialog("close"); } },close: function (event, ui) {$(this).remove(); },open : function() {var t = $(this).parent();var  w = $(window);var www = (t.width() / 2);t.offset({top:  (w.height() / 2) - (t.height() / 2),left: (w.width() / 2) - (t.width() / 2)});},resizable: false,position:"center",title: title,witdh:'auto',height: 'auto',overflow: 'auto',fluid:true,modal: true}).html(message);}});
$.fn.extend({onNumeric: function(fn){if($.isFunction(fn)){$(this).bind("paste", function(e){return false;});$(this).bind("drop", function(e){return false;});this.each(function(){$(this).keypress(function(e){var isFf = !(window.mozInnerScreenX == null);if(isFf){if((e.which >= 48 && e.which <= 57) || (e.which == 0) || (e.which == 8)){}else{e.preventDefault();}}else{if(e.which >= 48 && e.which <= 57){}else{e.preventDefault();}}});});}}});
function updateText(event){var input = $(this);setTimeout(function(){var val = input.val();if(val != ''){input.parent().addClass('floating-placeholder-float');}else{input.parent().removeClass('floating-placeholder-float');}},1);}
function showError(o){o.parent('LI').addClass('has-error');}function hideError(o){o.parent('LI').removeClass('has-error');}
function comboError(o){$(".chzn-container-single .chzn-default").attr('style', 'border-color: #a94442;-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);');}
function delComboError(o){$("#grado_chzn").find("A.chzn-single").removeAttr("style");}
function showMessageError(o,mg){var msg = "<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert'>×</button><span class='glyphicon glyphicon-exclamation-sign'></span><strong> "+mg+"</strong></div>";o.parent().parent().find("LI:first").html(msg);}
function hideMessageError(o){o.parent().parent().find("LI:first").html("");}
function autoCts(o){$(o).autocomplete({source: "buscarCts",minLength:2,select: function(event,ui){$("#cct").val(ui.item.value).focus();return false;}});}
function fixColum(){if($("#myDivcolum").size() > 0){var $cache = $('#fixx');var off = $("#myDivcolum").offset().top -30;if($(window).scrollTop() >= off && $("#showHideEncuesta").is(":visible")){$('#fixx').removeClass("hiden");$cache.css({'position': 'fixed','top': '10px','bottom': '90px'});}else{$('#fixx').addClass("hiden");$cache.css({'position': 'relative','top': 'auto'});}}}
function scrollToTop(){verticalOffset = typeof(verticalOffset) != 'undefined' ? verticalOffset : 0;element = $('body');offset = element.offset();offsetTop = offset.top;$('html, body').animate({scrollTop: offsetTop}, 500, 'linear');}
function fluidDialog(){var $visible = $(".ui-dialog:visible");$(".ui-dialog-titlebar-close").attr('title','Cerrar');$visible.each(function (){var $this = $(this);var dialog = $this.find(".ui-dialog-content").data("ui-dialog");if (dialog.options.fluid){var wWidth = $(window).width();if (wWidth < (parseInt(dialog.options.maxWidth) + 50)){$this.css("max-width", "90%");} else {$this.css("max-width", dialog.options.maxWidth + "px");}dialog.option("position", dialog.options.position);}});}
function step(){jQuery(function(e){e("form#wrapped").attr("action","guardarEncuesta");e("#review_container").wizard({stepsWrapper:"#wrapped",submit:".submit",beforeSelect:function(t,n){
if(e("input#website").val().length!=0){return false;}if(!n.isMovingForward)return true;var r=e(this).wizard("state").step.find(":input");
if(n.stepsComplete == 1){var hh = 0;var hl = 0;if($.trim($("#cct").val()).length == 0){showError($("#cct"));hh++;}else{hideError($("#cct"));}if($.trim($("#zona").val()).length == 0){showError($("#zona"));hh++;}else{hideError($("#zona"));}if($.trim($("#cct").val()).length != 10){showError($("#cct"));hl++;}else{hideError($("#cct"));}if($.trim($("#zona").val()).length != 3){showError($("#zona"));hl++;}else{hideError($("#zona"));}if(hh > 0){showMessageError($("#cct"),"Campos obligatorios");return false;}else{hideMessageError($("#cct"));}if(hl > 0){showMessageError($("#cct"),"Revise la información ingresada");return false;}else{hideMessageError($("#cct"));}$.ajaxSetup({async:false});var fine = 0;$.post("validarCct",{csrf_poll_tok_name:$.trim($("#token").val()),cct:$.trim($("#cct").val()),zona:$.trim($("#zona").val())},function (r){fine = r;});$.ajaxSetup({async:true});if(fine == 0){showMessageError($("#cct"),"La clave del Ct o la Zona es incorrecta");return false;}else{hideMessageError($("#cct"));}window.onbeforeunload = function (e) {e = e || window.event;if (e) {e.returnValue = '¿Está seguro de que desea abandonar la encuesta?';}return '¿Está seguro de que desea abandonar la encuesta?';};}
if(n.stepsComplete == 2){var mt = 0;if($.trim($("#app").val()).length == 0){showError($("#app"));mt++;}else{hideError($("#app"));}if($.trim($("#nombres").val()).length == 0){showError($("#nombres"));mt++;}else{hideError($("#nombres"));}if($.trim($("#fecha").val()).length == 0){showError($("#fecha"));mt++;}else{hideError($("#fecha"));}if($.trim($("#edad").val()).length == 0){showError($("#edad"));mt++;}else{hideError($("#edad"));}if($.trim($("#grado").val()) <= 0){comboError($("#grado"));mt++;}else{delComboError($("#grado"));}if($("#otros").size() > 0 && $.trim($("#otros").val()).length == 0){showError($("#otros"));mt++;}else{hideError($("#otros"));}if($.trim($("#cargo").val()).length == 0){showError($("#cargo"));mt++;}else{hideError($("#cargo"));}if($.trim($("#funcion").val()).length == 0){showError($("#funcion"));mt++;}else{hideError($("#funcion"));}if($.trim($("#horas").val()).length == 0){showError($("#horas"));mt++;}else{hideError($("#horas"));}if($.trim($("#antiguedad").val()).length == 0){showError($("#antiguedad"));mt++;}else{hideError($("#antiguedad"));}if(mt > 0){showMessageError($("#app"),"Campos obligatorios");return false;}else{hideMessageError($("#app"));}}
if(n.stepsComplete == 3){if ($('#showHideEncuesta').is(':hidden')){$.alert('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert">×</button><span class="glyphicon glyphicon-exclamation-sign"></span><strong> Primero debe empezar a contestar la encuesta.</strong></div>',"Mensaje");fluidDialog();return false;}var _names = [];$("input:radio").each( function(i,e){var name = $(this).attr("name");if($.inArray(name, _names) <= -1){_names.push(name);$("input[name="+name+"]").parent().parent().attr('style','');}});var valid = 0;var _fisrt = "";$(_names).each( function(i,e){if(!$("input[name="+e+"]:checked").val()){if(valid == 0){_fisrt = e;}valid++;}});if(valid > 0){var off = $("input[name="+_fisrt+"]").parent().parent().offset().top;$('html, body').animate({ scrollTop: off}, 100);$("input[name="+_fisrt+"]").parent().parent().attr('style', 'border-color: #a94442;-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);');$("input[name="+_fisrt+"]").focus();setTimeout( function (){$.alert('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert">×</button><span class="glyphicon glyphicon-exclamation-sign"></span><strong> Todavía faltan preguntas por contestar.</strong></div>',"Mensaje");fluidDialog();},100);return false;}}
}});e("#progressbar").progressbar();e("#review_container").wizard({afterSelect:function(t,n){e("#progressbar").progressbar("value",n.percentComplete);e("#location").text("("+n.stepsComplete+"/"+n.stepsPossible+")");if(n.stepsComplete == 1){$("#app").focus();}if(n.stepsComplete == 2){var off = $("#top-wizard").offset().top;$('html, body').animate({ scrollTop: off}, 100);}}});});}
$(document).ready(function(){
$('.floating-placeholder input').keydown(updateText);$('.floating-placeholder input').change(updateText);$("LI input[type=text]").attr("autocomplete","off");
$(window).resize(function(){fluidDialog();});$(document).on( 'scroll', function(){if($(window).scrollTop() > 100) {$('.scrollTop').addClass('showUp');}else{$('.scrollTop').removeClass('showUp');}});$('.scrollTop').on('click', scrollToTop);$(window).scroll(fixColum);fixColum();$("#cct").focus();$("#grado").change( function(){if($(this).val() == 2 || $(this).val() == 5){$("#txtCampo").removeClass('hiden');$("#txtCampo").html('<input type="text" name="otros" id="otros" class="form-control mbot10 upper" /><label for="otros">ESPECIFIQUE *</label>');$('.floating-placeholder input').keydown(updateText);$('.floating-placeholder input').change(updateText);}else{$("#txtCampo").addClass('hiden');$("#txtCampo").html('');}});$(".selectCombo").chosen({allow_single_deselect: true});$(".fecha").datepicker({dateFormat: 'dd/mm/yy',yearRange: '1950:2015',changeMonth: true,changeYear: true,dayNamesMin: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun','Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']}).blur(function(){var filter = /^\d{2}\/\d{2}\/\d{4}$/;if(!filter.test($(this).val())){$(this).val(null);}});$("#zona").onNumeric(function(){});$("#edad").onNumeric(function(){});autoCts($("#cct"));step();$("#btnBegin").click(function(event){$("#beginPoll").remove();$("#showHideEncuesta").removeClass('hiden');var off = $("#showHideEncuesta").offset().top;$('html, body').animate({ scrollTop: off}, 100);$.post("obtenerFecha",{id:1,csrf_poll_tok_name:$.trim($("#token").val())}, function(r){$("#ffi").val(r);});});$("#btnFinish").click(function(event) {$(this).replaceWith('<div id="guardando" class="btn-success btn-lg disabled ui-state-disabled"><span class="glyphicon glyphicon-ok"></span> ENVIANDO...</div>');window.onbeforeunload = function () {};$("form#wrapped").submit();});});